SistemaTaller/Controllers/Usuarios1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaTaller.Models;

namespace SistemaTaller.Controllers
{
    public class Usuarios1Controller : Controller
    {
        private readonly TallerContext _context;

        public Usuarios1Controller(TallerContext context)
        {
            _context = context;
        }

        // GET: Usuarios1
        public async Task<IActionResult> Index(string id)
        {
            var Usuarios = from m in _context.Usuarios
                         select m;

            if (!String.IsNullOrEmpty(id))
            {
                Usuarios = Usuarios.Where(s => s.Nombre.Contains(id));
            }
            return View(await Usuarios.Where(s => s.Clave != "000").ToListAsync());
        }

        // GET: Usuarios1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.IdUsuarios == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUsuarios,Nombre,Clave,Cargo,Status")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUsuarios,Nombre,Clave,Cargo,Status")] Usuario usuario)
        {
            if (id != usuario.IdUsuarios)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.IdUsuarios))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.IdUsuarios == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.IdUsuarios == id);
        }
    }
}

SistemaTaller/Views/Usuarios1/Create.cshtml
@model SistemaTaller.Models.Usuario

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <select asp-for="Cargo" class="form-control">
                    <option value="Mecánico">Mecánico</option>
                    <option value="Supervisor">Supervisor</option>
                    <option value="Representante">Representante</option>

                </select>
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="1">Activo</option>
                    <option value="0">Inactivo</option>
                </select>

                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaTaller/Views/Usuarios1/Delete.cshtml
@model SistemaTaller.Models.Usuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clave)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cargo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdUsuarios" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SistemaTaller/Views/Usuarios1/Details.cshtml
@model SistemaTaller.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clave)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cargo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdUsuarios">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SistemaTaller/Views/Usuarios1/Edit.cshtml
@model SistemaTaller.Models.Usuario

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdUsuarios" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <select asp-for="Cargo" class="form-control">
                    <option value="Mecánico">Mecánico</option>
                    <option value="Supervisor">Supervisor</option>
                    <option value="Representante">Representante</option>

                </select>
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="1">Activo</option>
                    <option value="0">Inactivo</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaTaller/Views/Usuarios1/Index.cshtml
@model IEnumerable<SistemaTaller.Models.Usuario>

@{
    ViewData["Title"] = "Index";
}

<h1>Usuarios</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Usuarios1" asp-action="Index">
    <p class="row">
       <input placeholder="Nombre" class="form-control col-sm-4" type="text" name="id" />
        <input class="btn btn-success" type="submit" value="Filter" />
    </p>
</form>
<table class="table table-bordered table-striped" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Cargo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
          
            <td>
                @Html.DisplayFor(modelItem => item.Cargo)
            </td>
            <td>
                @if (item.Status == 0)
                {
                    <p class="btn btn-danger">Inactivo</p>
                }
                else
                {
                    <p class="btn btn-success">Activo</p>

                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdUsuarios"><button class="btn btn-warning"><i class="fas fa-edit"></i></button> </a>
                <a asp-action="Details" asp-route-id="@item.IdUsuarios"> <button class="btn btn-info"><i class="fas fa-eye"></i></button> </a>
               <a asp-action="Delete" asp-route-id="@item.IdUsuarios"> <button class="btn btn-danger" > <i class="fas fa-trash-alt"></i></button></a>
            </td>
        </tr>
}
    </tbody>
</table>